apiVersion: v1
kind: Service
metadata:
  name: camunda
  labels:
    app: camunda
    tier: backend
    group: java
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: camunda
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda
  template:
    metadata:
      labels:
        app: camunda
        tier: backend
        group: java
    spec:
      containers:        
      - name: camunda
        image: camunda/camunda-bpm-platform
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 8080
          name: camunda    
